# Generated by Django 2.1.9 on 2020-04-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Paper_Type', models.CharField(max_length=100)),
                ('Product_Category', models.CharField(max_length=100)),
                ('Product_Thickness', models.CharField(max_length=100)),
                ('Product_Lamination', models.CharField(max_length=100)),
                ('Product_Quantity', models.CharField(max_length=100)),
                ('Product_Print_Sides', models.CharField(max_length=100)),
                ('Product_Color', models.CharField(max_length=100)),
                ('Product_Size', models.CharField(max_length=100)),
                ('Product_Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ProductData',
            },
        ),
    ]
