# Generated by Django 2.1.1 on 2020-08-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='CartData',
        ),
        migrations.DeleteModel(
            name='gallery',
        ),
        migrations.DeleteModel(
            name='OrderData',
        ),
        migrations.DeleteModel(
            name='PaperTypeData',
        ),
        migrations.DeleteModel(
            name='ProductData',
        ),
        migrations.DeleteModel(
            name='Productdesign',
        ),
        migrations.DeleteModel(
            name='ProductDesignData',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='ResellerData',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
