# Generated by Django 2.1.1 on 2020-08-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printapp', '0002_auto_20200819_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bannerid', models.CharField(max_length=100)),
                ('first', models.ImageField(blank=True, upload_to='banner1/')),
                ('second', models.ImageField(blank=True, upload_to='banner2/')),
            ],
        ),
        migrations.CreateModel(
            name='CartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_ID', models.CharField(max_length=100)),
                ('Order_ID', models.CharField(max_length=50)),
                ('User_Email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CartData',
            },
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_ID', models.CharField(max_length=100)),
                ('galleryimage', models.ImageField(upload_to='gallerypics/')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=100)),
                ('Order_Date', models.DateField(auto_now=True)),
                ('Product_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
                ('Design_ID', models.CharField(max_length=100)),
                ('Payment_ID', models.CharField(max_length=100)),
                ('multiply_by_quantity', models.CharField(max_length=100)),
                ('Detail_File', models.FileField(default='orderdetailfile/nodata.png', upload_to='orderdetailfile/')),
                ('logo', models.FileField(default='logo/nologo.png', upload_to='logo/')),
                ('Name', models.CharField(default='', max_length=100)),
                ('companyname', models.CharField(default='', max_length=100)),
                ('companygmail', models.CharField(default='', max_length=100)),
                ('GSTN', models.CharField(default='', max_length=100)),
                ('weblink', models.CharField(default='', max_length=100)),
                ('ph1', models.CharField(default='', max_length=100)),
                ('ph2', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=1000)),
                ('otherdetails', models.CharField(default='', max_length=1000)),
                ('paper_weight', models.CharField(default='Standard', max_length=100)),
                ('Corner', models.CharField(default='Standard', max_length=100)),
                ('Order_Status', models.CharField(max_length=100)),
                ('side', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('lamination', models.CharField(blank=True, max_length=100)),
                ('deliverycharge', models.CharField(blank=True, max_length=100)),
                ('deliveryaddress', models.CharField(blank=True, max_length=1000)),
                ('productamount', models.FloatField(blank=True)),
                ('Total_Amount', models.CharField(max_length=100)),
                ('Amount_to_Pay', models.CharField(max_length=100)),
                ('Rest_Amount', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OrderData',
            },
        ),
        migrations.CreateModel(
            name='PaperTypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_ID', models.CharField(max_length=100)),
                ('Paper_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PaperTypeData',
            },
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(max_length=100)),
                ('Product_Type', models.CharField(default='', max_length=100)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Paper_Type', models.CharField(default='', max_length=100)),
                ('Product_Category', models.CharField(default='', max_length=100)),
                ('Product_Thickness', models.CharField(default='', max_length=100)),
                ('Product_Lamination', models.CharField(default='', max_length=100)),
                ('Product_Quantity', models.CharField(max_length=100)),
                ('Product_Print_Sides', models.CharField(default='', max_length=100)),
                ('Product_Color', models.CharField(default='', max_length=100)),
                ('Product_Size', models.CharField(max_length=100)),
                ('Product_Price', models.CharField(max_length=100)),
                ('Product_Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ProductData',
            },
        ),
        migrations.CreateModel(
            name='Productdesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_ID', models.CharField(max_length=100)),
                ('Product_ID', models.CharField(max_length=100)),
                ('Corner', models.CharField(default='', max_length=100)),
                ('Design_Image', models.ImageField(upload_to='subproductdesignes/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDesignData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_ID', models.CharField(max_length=100)),
                ('Product_ID', models.CharField(max_length=100)),
                ('Design_Image', models.ImageField(upload_to='productdesignes/')),
            ],
            options={
                'db_table': 'PropertyDesignData',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(max_length=100)),
                ('name', models.TextField(default='')),
                ('phone', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('subject', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('Date', models.DateField(auto_now=True)),
                ('star1', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResellerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reseller_ID', models.CharField(max_length=100)),
                ('Reseller_First_Name', models.CharField(max_length=100)),
                ('Reseller_Last_Name', models.CharField(max_length=100)),
                ('Reseller_Gender', models.CharField(max_length=100)),
                ('Reseller_Email', models.CharField(max_length=100)),
                ('Reseller_Phone', models.CharField(max_length=100)),
                ('Reseller_Address', models.CharField(max_length=1000)),
                ('Reseller_City', models.CharField(max_length=100)),
                ('Reseller_State', models.CharField(max_length=100)),
                ('Reseller_GSTIN', models.CharField(max_length=100)),
                ('Reseller_PAN', models.CharField(max_length=100)),
                ('Reseller_Password', models.CharField(max_length=100)),
                ('Reseller_Status', models.CharField(max_length=100)),
                ('Adhaar', models.ImageField(upload_to='reselleradhaar/')),
                ('Profile', models.ImageField(upload_to='resellerprofile/')),
                ('conditions', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ResellerData',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testi_ID', models.CharField(max_length=100)),
                ('testiname', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=400)),
                ('pic', models.ImageField(upload_to='testipic/')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=100)),
                ('User_First_Name', models.CharField(max_length=100)),
                ('User_Last_Name', models.CharField(max_length=100)),
                ('User_Gender', models.CharField(max_length=100)),
                ('User_Email', models.CharField(max_length=100)),
                ('User_Phone', models.CharField(max_length=100)),
                ('User_Address', models.CharField(max_length=1000)),
                ('User_City', models.CharField(max_length=100)),
                ('User_State', models.CharField(max_length=100)),
                ('User_Password', models.CharField(max_length=100)),
                ('conditions', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
    ]
