# Generated by Django 2.1.9 on 2020-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0003_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='User_Gender',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
