# Generated by Django 2.1.1 on 2020-08-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0003_banner_cartdata_gallery_orderdata_papertypedata_productdata_productdesign_productdesigndata_rating_r'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderData',
        ),
    ]
