# Generated by Django 2.1.1 on 2020-08-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0004_delete_orderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=100)),
                ('Order_Date', models.DateField(auto_now=True)),
                ('Product_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
                ('Design_ID', models.CharField(max_length=100)),
                ('Payment_ID', models.CharField(max_length=100)),
                ('multiply_by_quantity', models.CharField(max_length=100)),
                ('Detail_File', models.FileField(default='orderdetailfile/nodata.png', upload_to='orderdetailfile/')),
                ('logo', models.FileField(default='logo/nologo.png', upload_to='logo/')),
                ('Name', models.CharField(default='', max_length=100)),
                ('companyname', models.CharField(default='', max_length=100)),
                ('companygmail', models.CharField(default='', max_length=100)),
                ('GSTN', models.CharField(default='', max_length=100)),
                ('weblink', models.CharField(default='', max_length=100)),
                ('ph1', models.CharField(default='', max_length=100)),
                ('ph2', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=1000)),
                ('otherdetails', models.CharField(default='', max_length=1000)),
                ('paper_weight', models.CharField(default='Standard', max_length=100)),
                ('Corner', models.CharField(default='Standard', max_length=100)),
                ('Order_Status', models.CharField(max_length=100)),
                ('side', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('lamination', models.CharField(blank=True, max_length=100)),
                ('deliverycharge', models.CharField(blank=True, max_length=100)),
                ('deliveryaddress', models.CharField(blank=True, max_length=1000)),
                ('productamount', models.FloatField(blank=True)),
                ('Total_Amount', models.CharField(max_length=100)),
                ('Amount_to_Pay', models.CharField(max_length=100)),
                ('Rest_Amount', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OrderData',
            },
        ),
    ]
