# Generated by Django 2.1.1 on 2020-04-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0005_productdesigndata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reseller_ID', models.CharField(max_length=100)),
                ('Reseller_fullname', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Business_Name', models.CharField(max_length=100)),
                ('Business_Type', models.CharField(max_length=100)),
                ('Gstn', models.CharField(max_length=100)),
                ('Pancard_No', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('Establish', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Resellerpic')),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ResellerData',
            },
        ),
    ]
