# Generated by Django 2.1.9 on 2020-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0005_productdesigndata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reseller_ID', models.CharField(max_length=100)),
                ('Reseller_First_Name', models.CharField(max_length=100)),
                ('Reseller_Last_Name', models.CharField(max_length=100)),
                ('Reseller_Gender', models.CharField(max_length=100)),
                ('Reseller_Email', models.CharField(max_length=100)),
                ('Reseller_Phone', models.CharField(max_length=100)),
                ('Reseller_Address', models.CharField(max_length=1000)),
                ('Reseller_City', models.CharField(max_length=100)),
                ('Reseller_State', models.CharField(max_length=100)),
                ('Reseller_GSTIN', models.CharField(max_length=100)),
                ('Reseller_PAN', models.CharField(max_length=100)),
                ('Reseller_Password', models.CharField(max_length=100)),
                ('Reseller_Status', models.CharField(max_length=100)),
                ('Adhaar', models.ImageField(upload_to='reselleradhaar/')),
                ('Profile', models.ImageField(upload_to='resellerprofile/')),
            ],
            options={
                'db_table': 'ResellerData',
            },
        ),
    ]
