# Generated by Django 2.1.9 on 2020-04-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0006_resellerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='Product_Price',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
