# Generated by Django 2.1.1 on 2020-04-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0008_productdesigndata_design_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=100)),
                ('Product_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
                ('Design_ID', models.CharField(max_length=100)),
                ('Order_Status', models.CharField(max_length=100)),
                ('Detail_File', models.FileField(upload_to='orderdetailfile/')),
            ],
            options={
                'db_table': 'OrderData',
            },
        ),
    ]
