# Generated by Django 2.1.1 on 2020-04-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0010_orderdata_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='Total_Amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
