# Generated by Django 2.1.1 on 2020-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0011_orderdata_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='Amount_to_Pay',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdata',
            name='Rest_Amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
