# Generated by Django 2.1.1 on 2020-05-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0013_cartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='User_Email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
