# Generated by Django 2.1.1 on 2020-05-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0014_cartdata_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='Order_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
