# Generated by Django 2.1.1 on 2020-06-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0015_orderdata_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='Detail_File',
            field=models.FileField(blank=True, null=True, upload_to='orderdetailfile/'),
        ),
    ]
