# Generated by Django 2.1.1 on 2020-06-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0016_auto_20200602_1217'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table=None,
        ),
    ]
