# Generated by Django 2.1.1 on 2020-06-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0018_auto_20200602_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResellerData',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
