# Generated by Django 2.1.1 on 2020-06-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0020_resellerdata_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryimage', models.ImageField(upload_to='gallerypics/')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
    ]
