# Generated by Django 2.1.1 on 2020-06-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0021_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
