# Generated by Django 2.1.1 on 2020-06-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0022_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_ID', models.CharField(max_length=100)),
                ('galleryimage', models.ImageField(upload_to='gallerypics/')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
    ]
