# Generated by Django 2.1.1 on 2020-06-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0023_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='Detail_File',
        ),
    ]
