# Generated by Django 2.1.1 on 2020-06-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0024_remove_orderdata_detail_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderData',
        ),
    ]
