# Generated by Django 2.1.1 on 2020-06-19 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0026_orderdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderData',
        ),
    ]
