# Generated by Django 2.1.1 on 2020-06-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0027_delete_orderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=100)),
                ('Order_Date', models.DateField(auto_now=True)),
                ('Product_ID', models.CharField(max_length=100)),
                ('User_ID', models.CharField(max_length=100)),
                ('Design_ID', models.CharField(max_length=100)),
                ('Payment_ID', models.CharField(max_length=100)),
                ('multiply_by_quantity', models.CharField(max_length=100)),
                ('Detail_File', models.FileField(default='', upload_to='orderdetailfile/')),
                ('Name', models.CharField(default='', max_length=100)),
                ('companyname', models.CharField(default='', max_length=100)),
                ('companygmail', models.CharField(default='', max_length=100)),
                ('GSTN', models.CharField(default='', max_length=100)),
                ('ph1', models.CharField(default='', max_length=100)),
                ('ph2', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=1000)),
                ('otherdetails', models.CharField(default='', max_length=1000)),
                ('Order_Status', models.CharField(max_length=100)),
                ('Total_Amount', models.CharField(max_length=100)),
                ('Amount_to_Pay', models.CharField(max_length=100)),
                ('Rest_Amount', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OrderData',
            },
        ),
    ]
